### ISSUE TITLE
output format common support .csv

### ISSUE THREAD

**Issue by federicamas** [MCFpy/mcf#11]
https://github.com/MCFpy/mcf/blob/91caf98c7b7ad40dcf9d20c327b3d3a289de8c01/mcf/mcf_common_support_functions.py#L357C9-L357C51

Difficult  (or maybe it is me) to extract results when reading the csv in python. I think is still a dictionary and it would be easier to have a df to be able to plot the propensity scores by yourself, as an alternative to the already existing pdf (for example for our paper the legend is too small and i would like to reproduce the plot by myself):

![image](https://github.com/MCFpy/mcf/assets/104630003/b077b4e4-e662-413e-813e-0b837490192e)

**Comment by MichaelLechner** [comment]
Issue will be resolved in 0.6.0 (properly labeled DataFrames stored in csv files; pickle-Files are not ideal on some systems).
