### ISSUE TITLE
necessary resources?

### ISSUE THREAD

**Issue by joostbollens** [MCFpy/mcf#2]
[@hannahbus](https://github.com/hannahbus) , indeed a nicely documented package. I have already been experimenting a bit with the example programme from your tutorial, and it works without any problem. However, as soon as we scale up to a problem with more observations and features, sooner or later it crashes. Our IT department indicated to me that this is probably due to the environment I am working in: a docker environment on a workbench. More specifically, ray would not work well in this context.
They advise me to either switch to bare metal or move out to a cloud environment. The latter is far from obvious for privacy reasons.
What I actually wanted to ask, could you give an indication of what kind of environment you guys use to run somewhat larger samples, e.g. how much memory, how many cores etc? Thanks in advance, and definitely continue working on this nice package!

**Comment by hannahbus** [comment]
@joostbollens, thanks for the great feedback. Concerning your question, I would like to refer you to the replication repository of our paper, which you find here https://github.com/MCFpy/replication-BBL_2022. In the ReadMe.pdf, there is a section on Computational Requirements, in which you will find the specification of the machine we deployed-- including no. of cores and RAM. I am not sure Ray requires a cloud environment. We run it on our local machines (laptops) and servers. We tested both Unix-based OS and Windows. All worked fine. Please reach out should the issue persist.
