### ISSUE TITLE
Error on install on Python 3.10 -  update setup.py to exclude importlib

### ISSUE THREAD

**Issue by paluigi** [MCFpy/mcf#5]
I tried to install mcf on Python 3.10 (Ubuntu 22.04), but I encountered an error:

```
Collecting importlib>=1.0.4 (from mcf)
  Using cached importlib-1.0.4.zip (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I cloned the package locally, and in order to complete a successful installation I had to comment line 33 in setup.py . importlib is now part of the standard library (at least in Python 3.10 and onwards), so it should not be installed.

I think it may be possible to insert a check in setup.py to only install importlib if Python is older than a certain version...if I have the chance I'll try to make this change and open a pull request at some point.

**Comment by hbodory** [comment]
Thanks Luigi, the next version will fix this issue.
